name: Docker CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  Build-Push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lidorlg/node-hello-lidor-new:latest
    - name: login to docker hub
      run: docker login -u lidorlg -p {{ secrets.dockerhub_password }}

    - name: Push the Docker image
      run: docker push lidorlg/node-hello-lidor-new:latest
